# Tomcat
server:
  port: 10000
  servlet:
    context-path: /article
# 注册中心 配置中心
spring:
  application:
    name: blog-article
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: localhost:8848
      config:
        import-check:
          enabled: false
  
#      config:
#        # 配置中心地址
#        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: 123456
    virtual-host: /
# 定义类型处理器的路径
mybatis-plus:
  type-handlers-package: com.xb.blog.article.config.mybatis.typeHandler