# Tomcat
server:
  port: 9000
  servlet:
    context-path: /message
# 注册中心 配置中心
spring:
  application:
    name: blog-message
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: nacos:8848
      config:
        import-check:
          enabled: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: 123456
    virtual-host: /
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/blog
    username: root
    password: root
  redis:
    host: redis
    port: 6379
#      config:
#        # 配置中心地址
#        server-addr: nacos:8848